project_id = "tmmeymhaxkrvngjfhave"

[functions.sitemap]
verify_jwt = false

[functions.og-post]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.ai-v1-chat]
verify_jwt = false

[functions.og-profile]
verify_jwt = false