// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Anon/publishable keys are safe to ship in client code — they're protected by
// Supabase Row-Level Security. Env vars override these defaults when set.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://fwjxhozxlucaywpavznu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3anhob3p4bHVjYXl3cGF2em51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1ODcyNTIsImV4cCI6MjA5NzE2MzI1Mn0.RlyLyTfab2fe__AXpNbewKvb1mmeNs53IzLGLQwD75Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});